/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    ChatHistory: typeof import('./src/components/ChatHistory.vue')['default']
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    ChatWelcome: typeof import('./src/components/ChatWelcome.vue')['default']
    ChatWindow: typeof import('./src/components/ChatWindow.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Knowledge: typeof import('./src/components/Knowledge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserLogin: typeof import('./src/components/UserLogin.vue')['default']
  }
}
